# Generated by Django 6.0.5 on 2026-05-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalizedemissionrecord',
            old_name='unit',
            new_name='original_unit',
        ),
    ]
