# Generated by Django 6.0.5 on 2026-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rename_unit_normalizedemissionrecord_original_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='suspicious_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
